name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - ros2

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8, pep257, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@main
      - uses: ros-tooling/setup-ros@0.1.2
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-lint@0.1.1
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name: |
            create2_autonomy
            create2_navigation
            create2_vision
      - uses: ros-tooling/action-ros-ci@0.1.1
        with:
          package-name: create2_navigation
          target-ros2-distro: foxy
